[browser]
gatherUsageStats = false

[server]
headless = true
runOnSave = true

[theme]
primaryColor = "#6D5DFB"
backgroundColor = "#F7F7F5"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#18181B"
font = "sans serif"
